### ISSUE TITLE
As user I want to view the schedule

### ISSUE THREAD

**Issue by ikke6992** [ikke6992/rooster#27]
A normal user should be able to view the schedule. Users should not be able to change the scheduling in any way. They should be able to download or print the schedule.

**Comment by RaafiKuijper** [comment]
login -> admin

admin:
- change everything

user (not logged in): 
- can only view
 - no override/drag drop on schedule view
 - no access to view groups/teachers
 - no remove/add freedays on view freedays
 - no access to notes(?)
